config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :products #, only: [:index, :new, :edit, :show]
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  namespace :account do
    resources :orders
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  resources :cart_items
  root 'products#index'
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 JDStore
        <br>Design by PaulShu

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">JDStore </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to("Products", products_path)%>
            </li>
          </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to carts_path do %>
                  购物车 <i class="fa fa-shopping-cart"> </i> ( <%= current_cart.products.count %> )
                <% end %>
              </li>
              <% if !current_user %>
                <li><%= link_to("注册", new_user_registration_path) %> </li>
                <li><%= link_to(content_tag(:i, ' 登入', class: 'fa fa-sign-in'), new_user_session_path) %></li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hi!, <%= current_user.email %>
                      <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <% if current_user.admin? %>
                      <li>
                        <%= link_to(content_tag(:i, ' 后台管理', class: 'fa fa-destop'), admin_products_path)%>
                      </li>
                    <% end %>
                    <li> <%= link_to("个人订单列表", account_orders_path ) %> </li>
                    <li role="separator" class="divider"></li> <!-- divider是bootstrap dropdowns下的分隔功能，可将多个下拉菜单分开 -->
                    <li> <%= link_to(content_tag(:i, ' 登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
                  </ul>
                </li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->

</nav>